/*
 *  Copyright (C) 2012 Josh Bialkowski (jbialk@mit.edu)
 *
 *  This file is part of openbook.
 *
 *  openbook is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  openbook is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with openbook.  If not, see <http://www.gnu.org/licenses/>.
 */

/**
 *  @file   msg_gen/MessageStr.cpp
 *
 *  @date   May 12, 2013
 *  @author Josh Bialkowski (jbialk@mit.edu)
 *  @brief  Generated by message_map.pl
 */


#include "msg_gen/MessageId.h"
#include "msg_gen/MessageStr.h"

namespace   openbook {
namespace filesystem {
    
const char* g_msgIdStr[] =
{
    "QUIT",
    "PING",
    "PONG",
    "SET_DISPLAY_NAME",
    "SET_DATA_DIR",
    "SET_LOCAL_SOCKET",
    "SET_REMOTE_SOCKET",
    "SET_CLIENT_SOCKET",
    "SET_MAX_CONN",
    "LOAD_CONFIG",
    "SAVE_CONFIG",
    "ATTEMPT_CONNECT",
    "ADD_MOUNT_POINT",
    "REMOVE_MOUNT_POINT",
    "UI_REPLY",
    "GET_BACKEND_INFO",
    "PEER_LIST",
    "MOUNT_LIST",
    "START_SYNC",
    "LEADER_ELECT",
    "DH_PARAMS",
    "KEY_EXCHANGE",
    "CEK",
    "AUTH_REQ",
    "AUTH_CHALLENGE",
    "AUTH_SOLN",
    "AUTH_RESULT",
    "SUBSCRIBE",
    "UNSUBSCRIBE",
    "ID_MAP",
    "NODE_INFO",
    "SEND_TREE",
    "SEND_FILE",
    "NEW_VERSION",
    "REQUEST_FILE",
    "FILE_CHUNK",
    "DIR_CHUNK",
    "INVALID",
};



const char* messageIdToString( MessageId id )
{
    if( id < 0 || id > NUM_MSG )
        return g_msgIdStr[NUM_MSG];
    else
        return g_msgIdStr[id];
}

    
} //< namespace filesystem 
} //< namespace openbook

        
