# Openbook File System Client Configuration
# ----------------------------------------------------------------------------
#    This is a YAML document. See www.yaml.org for more information
#    about the document format

# this is the name which will be displayed on the server and other clients to
# identify this client. If you only mount one file system, consider using
# the machine hostname for this field
displayName : "Nadie"

# Storage location of client data. This is where the client will store files 
# that it generates for persistence, like a database of unsent messages, the
# real file sistem is also stored here
dataDir : "${CMAKE_CURRENT_BINARY_DIR}/data"

# local connections will be accepted on port number
localSocket :
    # Service to listen on, can be a service name if there is one registered
    # in /etc/services or simply a port number 
    service : 3030

# remote connections will be accepted on this interface
remoteSocket :
    # Address family of interface to bind to. Options are AF_INET (IPv4) or 
    # AF_INET6 (IPv6), or AF_UNSPEC to pick any one which matches the following
    # criteria
    family : AF_INET
    
    # Interface to bind to. This is the IP address that the client uses to 
    # communicate with the server. You may enter a IPv4 (xxx.xxx.xxx.xxx) or IPv6 
    # (xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx) address, a hostname 
    # (obfs.openbk.net), or the string "any" to bind to any available interface
    node : any
    
    # Service to listen on, can be a service name if there is one registered
    # in /etc/services or simply a port number 
    service : 3031
    
# if specified, remote connections which we instigate will made using the
# specified interface
clientSocket :
    # Address family of interface to bind to. Options are AF_INET (IPv4) or 
    # AF_INET6 (IPv6), or AF_UNSPEC to pick any one which matches the following
    # criteria
    family : AF_INET
    
    # Interface to bind to. This is the IP address that the client uses to 
    # communicate with the server. You may enter a IPv4 (xxx.xxx.xxx.xxx) or IPv6 
    # (xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx) address, a hostname 
    # (obfs.openbk.net), or the string "any" to bind to any available interface
    node : any

# maximum number of peer connections
maxConnections : 20

# mount points to install on startup
mountPoints :
    - mount  :  ./mountPoint_1  # where to mount
      reldir : /                # relative dir of real root to source files
      argv   : ["-s", "-d"]     # arguments to pass to fuse
    - mount  :  ./mountPoint_2  
      reldir : /
      argv   : ["-s", "-d"]





